# SPDX-License-Identifier: MPL-2.0
# This workflow is managed by gh actions-lock.
name: "⚙ Auto: Mirror to forges"
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  actions: read
  contents: read
jobs:
  mirror:
    uses: hyperpolymath/standards/.github/workflows/mirror-reusable.yml@5a597720580d12fa04d24e1b9e100e2eb8d6e653
    secrets: inherit
